Repository ShuyunFF2E/cloud-react, pull requests merged in 2020-04, with the labels that each got.

#245 [Modal]增加disabledOk属性，用于禁止点击确认按钮
  src/components/modal/demos/style.markdown
  src/components/modal/index.js
  src/components/modal/index.md
  src/components/modal/modal.js
Labels: feature, help wanted

#258 [Tag]修复点击事件获取不到event问题
  src/components/tag/index.js
Labels: bug

#257 :art: [select] 修改单选下拉样式（超长显示滚动条）
  src/components/select/views/single-select.js
Labels: bug

#267 [Tree]修复选中节点后切换回显数据选中节点状态未变化问题
  src/components/tree/index.js
  src/components/tree/store.js
Labels: bug

#290 Feat/tab
  src/components/tabs/demos/fixed.markdown
  src/components/tabs/index.js
  src/components/tabs/index.less
  src/components/tabs/index.md
Labels: feature

#300 :bug: [Tree] 输入关键字搜索，新增目录，清除搜索内容重新搜索，结果错误
  src/components/tree/index.js
  src/components/tree/store.js
Labels: bug

#301 :bug: [Modal] 拖动modal后，点击确定按钮，如果不关闭弹窗，弹窗位置异常
  src/components/modal/modal.js
Labels: bug

#302 :bug: [InputNumber] 无法输入 0.0x 0.00x
  src/components/input-number/index.js
  src/components/input-number/util.js
Labels: bug
