Repository ShuyunFF2E/cloud-react, pull requests merged in 2020-06, with the labels that each got.

#346 [Modal] 异步加载高度变化重新定位
  src/components/modal/modal.js
Labels: bug

#345 打包输出umd命名改造，支持script方式引用
  scripts/webpack.production.js
Labels: feature

#343 [Button] 添加按钮loading状态
  src/components/button/demos/loading.markdown
  src/components/button/index.js
  src/components/button/index.less
  src/components/modal/index.less
  src/components/modal/modal.js
Labels: feature

#344 [Input.Textarea] 增加计数器功能
  src/components/input/demos/textarea.markdown
  src/components/input/index.less
  src/components/input/index.md
  src/components/input/textarea.js
Labels: feature

#347 [Datepicker] 修复年月日最大值为当天不能确定的问题
  src/components/datepicker/date-picker/grid.js
  src/components/datepicker/demos/date-picker.markdown
Labels: bug

#348 💄[Icon] 更新icon图标，增加remark
  src/components/icon/demos/basic.markdown
  src/components/icon/fonts/iconfont.woff
  src/components/icon/index.less
Labels: feature

#349 [Datepicker] 添加isAppendToBody 属性，选择日历弹框是否需要渲染在body上
  src/components/datepicker/common/picker.js
  src/components/datepicker/demos/date-picker.markdown
  src/components/datepicker/demos/time-picker.markdown
  src/components/datepicker/index.less
  src/components/datepicker/index.md
Labels: feature

#351 升级 gridmanager-react@0.4.13
  package.json
Labels: feature

#358 [toolTip]修改tooltip定位问题，container增加类名选择
  src/components/tooltip/demos/control.markdown
  src/components/tooltip/demos/placement.markdown
  src/components/tooltip/index.js
  src/components/tooltip/index.md
  src/components/tooltip/toolView.js
Labels: bug

#361 [Field] 修复field.(clear|reset|remove)调用后没有处理存储在__fieldsMeta__对象中的值问题
  src/components/field/index.js
Labels: bug

#365 组件创建 issue 模版更新
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#366 :bug: [InputNumber] value设置为0时渲染错误
  src/components/input-number/index.js
Labels: bug

#380 :sparkles:[tooltip]支持content传入jsx
  src/components/tooltip/demos/basic.markdown
  src/components/tooltip/demos/control.markdown
  src/components/tooltip/index.js
  src/components/tooltip/toolView.js
Labels: feature

#383 :bug: [Input] 修正 shouldComponent 逻辑；size等于small，hover时输入框变高
  src/components/input/demos/onChange.markdown
  src/components/input/index.js
  src/components/input/index.less
Labels: bug

#385 [Toggle]单元测试完成
  src/components/toggle/__tests__/__snapshots__/index.test.js.snap
  src/components/toggle/__tests__/index.test.js
  src/components/toggle/index.js
  src/components/toggle/index.md
Labels: feature

#409 ✅ [Checkbox] 添加单元测试
  src/components/checkbox/__test__/__snapshots__/group.test.js.snap
  src/components/checkbox/__test__/__snapshots__/index.test.js.snap
  src/components/checkbox/__test__/group.test.js
  src/components/checkbox/__test__/index.test.js
  src/components/checkbox/demos/basic.markdown
  src/components/checkbox/index.js
Labels: feature

#411 🚨 [checkbox] fix eslint error
  src/components/checkbox/__test__/group.test.js
  src/components/checkbox/__test__/index.test.js
Labels: bug

#412 🔧 alias jest config to resolve tests folder
  jest.config.js
  jsconfig.json
  src/components/button/__test__/index.test.js
  src/components/checkbox/__test__/index.test.js
  src/components/toggle/__tests__/index.test.js
  webpack.config.js
Labels: feature

#414 ✅ [Tips] 添加单元测试
  src/components/tips/__test__/__snapshots__/index.test.js.snap
  src/components/tips/__test__/index.test.js
Labels: feature

#413 ✅ [Input] 添加单元测试
  src/components/input/__test__/__snapshots__/input.test.js.snap
  src/components/input/__test__/__snapshots__/textarea.test.js.snap
  src/components/input/__test__/input.test.js
  src/components/input/__test__/textarea.test.js
  src/components/input/demos/textarea.markdown
  src/components/input/index.js
  src/components/input/textarea.js
Labels: feature

#418 🔥 [pagination] 移除
  scripts/generate-index.js
  src/components/pagination/demos/basic.markdown
  src/components/pagination/demos/change.markdown
  src/components/pagination/demos/jump.markdown
  src/components/pagination/demos/more.markdown
Labels: feature

#419 ✅ [Pagination] 添加单元测试
  src/components/pagination/__test__/__snapshots__/index.test.js.snap
  src/components/pagination/__test__/index.test.js
  src/components/pagination/index.js
Labels: feature

#422 ✅ [loading] 单元测试完成
  src/components/loading/__test__/__snapshots__/index.test.js.snap
  src/components/loading/__test__/index.test.js
  src/components/loading/index.js
Labels: feature

#421 ✅ [TablePagination] 添加单元测试
  src/components/pagination/index.js
  src/components/table-pagination/__test__/__snapshots__/index.test.js.snap
  src/components/table-pagination/__test__/index.test.js
  src/components/table-pagination/index.js
Labels: feature

#415 ✅ [InputNumber] unit test done
  src/components/input-number/__test__/__snapshots__/index.test.js.snap
  src/components/input-number/__test__/index.test.js
  src/components/input-number/demos/basic.markdown
  src/components/input-number/index.js
  src/components/input-number/index.md
  src/components/input-number/old.js
  src/components/input-number/util.js
Labels: feature

#420 ✅ [Radio] 添加单元测试
  src/components/radio/__test__/__snapshots__/group.test.js.snap
  src/components/radio/__test__/__snapshots__/index.test.js.snap
  src/components/radio/__test__/group.test.js
  src/components/radio/__test__/index.test.js
  src/components/radio/index.js
Labels: feature

#423 🥅 eslint waring auto fix
  package.json
Labels: feature, question
