Repository ShuyunFF2E/cloud-react, pull requests merged in 2020-07, with the labels that each got.

#424 ✅ [Step] 添加单元测试
  src/components/step/__test__/__snapshots__/index.test.js.snap
  src/components/step/__test__/__snapshots__/item.test.js.snap
  src/components/step/__test__/index.test.js
  src/components/step/__test__/item.test.js
Labels: feature

#426 ✅ [Message] 单元测试编写
  src/components/message/__test__/index.test.js
  src/components/message/index.js
Labels: feature

#429 :ambulance:优化Modal组件在iframe框架里面时组件能创建到顶层document结构，同时适配Select、Datepic…
  src/components/datepicker/common/picker.js
  src/components/message/index.js
  src/components/modal/config-provider.js
  src/components/modal/demos/basic.markdown
  src/components/modal/demos/iframe.markdown
  src/components/modal/index.js
  src/components/modal/index.md
  src/components/modal/modal.js
  src/components/modal/prompt.js
  src/components/select/index.js
  src/utils/__test__/getRootDocument.test.js
  src/utils/__test__/getRootWindow.test.js
  src/utils/get-root-document.js
  src/utils/get-root-window.js
  src/utils/get-styles.js
  src/utils/index.js
Labels: bug

#431 [Form] 新增表单提交失败时可让失败的第一个表单项滚动至可视区域特性
  src/components/field/index.js
  src/components/form/constants.js
  src/components/form/demos/basic-usage.markdown
  src/components/form/index.js
  src/components/form/index.md
Labels: feature

#432 新增轻量表格
  package.json
  src/components/icon/demos/basic.markdown
  src/components/icon/fonts/iconfont.woff
  src/components/icon/index.less
  src/components/pagination/tes/index.test1.js
  src/components/table-lite/__tests__/__snapshots__/index.test.js.snap
  src/components/table-lite/__tests__/index.test.js
  src/components/table-lite/demos/basic.markdown
  src/components/table-lite/demos/tree.markdown
  src/components/table-lite/index.js
  src/components/table-lite/index.less
  src/components/table-lite/index.md
Labels: feature

#434 [Tolltip] 优化组件实现方式，内容格式支持jsx组件和html内容
  package.json
  src/components/tooltip/demos/basic.markdown
  src/components/tooltip/demos/control.markdown
  src/components/tooltip/demos/placement.markdown
  src/components/tooltip/demos/theme.markdown
  src/components/tooltip/index.js
  src/components/tooltip/index.less
  src/components/tooltip/index.md
  src/components/tooltip/toolView.js
Labels: feature

#435 🔨 [pagination] 打包还原
  scripts/generate-index.js
  src/components/pagination/__test__/__snapshots__/index.test.js.snap
  src/components/pagination/__test__/index.test.js
Labels: feature

#436 [Modal]修复弹框组件在iframe场景下基础组件不在隔离容器内问题
  src/components/datepicker/common/picker.js
  src/components/modal/config-provider.js
  src/components/modal/constants.js
  src/components/modal/index.js
  src/components/modal/modal.js
  src/components/select/index.js
  src/components/tooltip/index.js
Labels: bug

#438 [Tooltip]修复content值渲染方式异常问题
  src/components/tooltip/toolView.js
Labels: feature

#444 ✅ [Select] 添加单元测试
  src/components/select/__test__/__snapshots__/index.test.js.snap
  src/components/select/__test__/__snapshots__/multi.test.js.snap
  src/components/select/__test__/index.test.js
  src/components/select/__test__/multi.test.js
  src/components/select/index.js
  src/components/select/views/multi-select.js
  src/components/select/views/selected.js
Labels: feature

#442 🐛 [InputNumber] value初始值为空问题修复
  .prettierignore
  src/components/input-number/index.md
  src/components/input-number/util.js
Labels: bug

#445 ✅ [Tabs] 添加单元测试
  src/components/pagination/index.js
  src/components/tabs/__test__/__snapshots__/index.test.js.snap
  src/components/tabs/__test__/index.test.js
  src/components/tabs/index.js
Labels: feature

#446 [Upload]Bug修复，增加新属性
  src/components/upload/constant.js
  src/components/upload/demos/basic.markdown
  src/components/upload/http.js
  src/components/upload/index.js
  src/components/upload/index.md
Labels: bug, feature

#449 ✅ [Tooltip] 增加单元测试
  package.json
  src/components/tooltip/__test__/index.test.js
  src/components/tooltip/demos/control.markdown
  src/components/tooltip/index.js
  src/components/tooltip/index.md
  tests/utils.js
Labels: feature

#450 🚑 [Tabs] unit test update
  src/components/tabs/__test__/__snapshots__/index.test.js.snap
  src/components/tabs/__test__/index.test.js
Labels: bug

#455 [Menu]增加Menu单元测试
  src/components/menu/__test__/__snapshots__/index.test.js.snap
  src/components/menu/__test__/index.test.js
  src/components/menu/context.js
  src/components/menu/demos/basic.markdown
  src/components/menu/demos/controlled.markdown
  src/components/menu/demos/header.markdown
  src/components/menu/demos/link.markdown
  src/components/menu/demos/source.markdown
  src/components/menu/index.js
  src/components/menu/index.md
  src/components/menu/menu-item.js
  src/components/menu/sub-menu.js
Labels: feature

#462 ✅ [Tooltip] 添加单元测试
  src/components/tooltip/__test__/index.test.js
  src/components/tooltip/index.js
Labels: feature

#463 ✨ [Select] 单选添加点击选项返回原始数据
  src/components/select/__test__/index.test.js
  src/components/select/demos/basic.markdown
  src/components/select/index.js
  src/components/select/index.md
Labels: feature

#467 :bug: [Modal]修复关闭弹框时控制台报错问题
  src/components/modal/modal.js
Labels: bug

#456 ✅[Form, Field] add unit test
  src/components/field/index.js
  src/components/form/__test__/__snapshots__/form.test.js.snap
  src/components/form/__test__/form.test.js
Labels: feature

#468 Table fold
  package.json
  src/components/table-lite/index.js
  src/components/table-lite/index.less
  src/components/table-lite/index.md
  src/components/table/demos/top-full.markdown
  src/components/table/index.less
Labels: bug, feature
