Repository ShuyunFF2E/cloud-react, pull requests merged in 2020-03, with the labels that each got.

#224 :sparkles: [Select] 多选下拉可自定义配置确认取消按钮模板
  src/components/select/demos/customConfirmBtn.markdown
  src/components/select/index.js
  src/components/select/index.md
  src/components/select/views/multi-select.js
Labels: feature

#227 :sparkles:[Modal]优化功能，修复bug
  src/components/modal/demos/basic.markdown
  src/components/modal/index.less
  src/components/modal/modal.js
Labels: bug, help wanted

#228 [Modal] 修复Modal组件body内容部分高度受外界影响问题
  src/components/modal/index.less
Labels: bug

#236 [Tree]修复已知bug，优化样式，增加新属性
  src/components/tree/demos/basicSelector.markdown
  src/components/tree/demos/multipleSelectedValue.markdown
  src/components/tree/index.js
  src/components/tree/index.less
  src/components/tree/index.md
  src/components/tree/menu.js
  src/components/tree/node.js
  src/components/tree/store.js
Labels: bug, feature, help wanted
