Repository ShuyunFF2E/cloud-react, pull requests merged in 2021-05, with the labels that each got.

#535 :sparkles: [tree] 增加breakCheeckbox属性支持复选框与文字分离
  src/components/tree/demos/basicSelector.markdown
  src/components/tree/index.js
  src/components/tree/index.less
  src/components/tree/index.md
  src/components/tree/node.js
Labels: bug, feature

#538 :bug: [Datepicker] 输入“1/31”，时间弹窗没有自动同步时间
  src/components/datepicker/utils.js
Labels: bug

#540 ✨ [Upload] 支持在 FormData 中传入额外参数
  src/components/upload/demos/basic.markdown
  src/components/upload/http.js
  src/components/upload/index.js
  src/components/upload/index.md
Labels: feature

#539 :bug: [Input] 表单中只有一个input时，回车导致页面刷新
  src/components/input/index.js
Labels: bug
